env:
    MANIFEST: https://github.com/PixelExperience/manifest.git -b thirteen
    DEVICE: r5x
    LOCAL_MANIFEST: https://github.com/eartinity/local_manifest -b PixelExperience 
    TARGET: vndk
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: aosp_$DEVICE-userdebug
    OUTPUT: PixelExperience*.zip

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 120m  
  container:
      image: shazuxdd/ubuntu:latest
      cpu: 8
      memory: 32G

  Setup-Environment_script:
      - ./setup.sh
  Sync_script:
      - ./sync.sh
  Post-Storage-Checker_script:
      - df -h
  Build_script:
      - ./build.sh
  Upload_script:
      - ./upload.sh
